version: '3'
services:
  web:
    # https://hub.docker.com/r/library/nginx/
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/log:/var/log/nginx:delegated
  php:
    # https://hub.docker.com/r/library/php/
#    image: php:7-fpm
#    image: php:7-fpm-alpine3.7
    build: docker/php-fpm
    image: tox-t3/php-7-fpm
    volumes:
      - .:/app:cached
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
#      - ./var/log/php:/var/log/php:delegated
    environment:
      - TYPO3_CONTEXT=Development
  composer:
    image: composer:latest
#    command: install
    volumes:
      - .:/app:cached
      - ./docker/composer:/tmp:delegated
  db:
    # https://hub.docker.com/r/library/mysql/
    image: mysql:5
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: tox_typo3
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
