version: '3'
services:
  http-svc:
    build:
      context: .
    image: tox-t3:local
    volumes:
      - .:/app:cached
      - ./docker/composer:/opt/composer:delegated
    working_dir: /app
    environment:
#      - PHP_IDE_CONFIG=serverName=tox-typo3.local
#      - XDEBUG_CONFIG=remote_host=192.168.178.22 idekey=PHPSTORM
      - LOCAL_USER_ID
      - DOCUMENT_ROOT=/app/public
      - SKIP_LOCKDOWN_DOCUMENT_ROOT=true
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: tox_typo3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
      - ./docker/backup/database:/tmp
    ports:
      - "3306:3306"
