EXTCONF:
    realurl:
        _DOMAINS:
            encode:
                - { GETvar: L, value: '0', useConfiguration: default.tld, urlPrepend: 'http://%env(TYPO3_ROUTING_HOSTNAME_DEFAULT)%' }
                - { GETvar: L, value: '1', useConfiguration: default.tld, urlPrepend: 'http://%env(TYPO3_ROUTING_HOSTNAME_EN)%' }
            decode:
                '%env(TYPO3_ROUTING_HOSTNAME_DEFAULT)%':
                    GETvars: { L: '0' }
                    useConfiguration: default.tld
                '%env(TYPO3_ROUTING_HOSTNAME_EN)%':
                    GETvars: { L: '1' }
                    useConfiguration: default.tld
        default.tld:
            init:
                enableCHashCache: true
                appendMissingSlash: 'ifNotFile'
                adminJumpToBackend: true
                enableUrlDecodeCache: true
                enableUrlEncodeCache: true
                emptyUrlReturnValue: /
                disableErrorLog: true
            pagePath:
                rootpage_id: '1'
                type: user
                userFunc: 'Tx\Realurl\UriGeneratorAndResolver->main'
                spaceCharacter: '-'
                languageGetVar: 'L'
                expireDays: 3
                dontResolveShortcuts: false
            fileName:
                defaultToHTMLsuffixOnPrev: false
        '%env(TYPO3_ROUTING_HOSTNAME_EN)%': 'default.tld'
        '%env(TYPO3_ROUTING_HOSTNAME_DEFAULT)%': 'default.tld'
