SC_OPTIONS:
    t3lib/class.t3lib_div.php:
        systemLogInit: true
        systemLog:
            - Helhum\TYPO3\ErrorHandling\Log\SysLogAdapter->log
SYS:
    debugExceptionHandler: Helhum\TYPO3\ErrorHandling\Error\DebugExceptionHandler
    errorHandler: Helhum\TYPO3\ErrorHandling\Error\ErrorHandler
    productionExceptionHandler: Helhum\TYPO3\ErrorHandling\Error\ProductionExceptionHandler
    systemLog: false
